# Generated by Django 5.1 on 2024-09-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customer_cin"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="cin",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
