# Generated by Django 5.1 on 2024-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful')], default='P', max_length=1, verbose_name='État de livraison'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix par article (DT)'),
        ),
    ]
